### PR TITLE
Added function to reset stats.

### PR DESCRIPTION
**Pull request by zaafar**

### CODE REVIEW

**Comment by Ellpeck** [comment]
I don't really see a reason for this to exist?

**Comment by zaafar** [comment]
oh yes, they are public! I can change them directly. my bad.

**Comment by zaafar** [comment]
Actually no, the "set" is private.

So basically this will allow me to reset the stats so I can gather more recent stats. Actually thinking about it again, I just want to reset the "[MAX](https://github.com/Ellpeck/Coroutine/blob/master/Coroutine/ActiveCoroutine.cs#L42)" stat.

**Comment by zaafar** [comment]
@Ellpeck  so I was thinking more about this a bit more. To make things more generic, rather than exposing MaxMoveNextTime and AverageMoveNextTime, If we just expose LastMoveNextTime (so basically TotalMoveNextTime, MoveNextCount and LastMoveNextTime ). I can do all the average, rolling average, maximum, min, sd on my side.

sounds good?

**Comment by zaafar** [comment]
I can create an MR if that sounds good to you.

**Comment by Ellpeck** [comment]
yea, that sounds good.

**Pull request closed without merging**
