### PR TITLE
Demostrate the issue and add unit test

### PR DESCRIPTION
**Pull request by zaafar**
WARNING: this fails the CI pipeline.

### CODE REVIEW

**Comment by zaafar** [comment]
the way i see it is that there can be 2 fixes.

(1) don't add/remove coroutines in raise event. This is very simple fix i.e. easy to test/read/understand.
(2) if we really want to add/remove corotuines in raise event. Let's not add/remove time based coroutines.

**Comment by Ellpeck** [comment]
We *do* really want to add/remove coroutines in raise event, because otherwise event-based coroutine logic depends on the `Tick` method, which I fundamentally dislike. Not removing time-based coroutines makes a lot of sense, so I'll work on that improvement right now.

**Comment by zaafar** [comment]
sounds good! once you do that I will do some more testing to make sure there aren't any loopholes. :)

**Comment by Ellpeck** [comment]
Thanks!

**Comment by zaafar** [comment]
Tested it. No issues left. Thanks!

**Pull request merged**
